[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "HOST=0.0.0.0 HOSTNAME=0.0.0.0 node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100
