[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100
